### PR TITLE
Issue#3

### PR DESCRIPTION
**Pull request by MarcinGladkowski**
Hi! I move some query methods to new repository files. That creates some more clear code in these views.

### CODE REVIEW

**Comment by sunboyy** [comment]
I currently have some functions implemented in `src/recallcard/core.php`. Could you make use of it or clean that piece of code with yours?

**Comment by MarcinGladkowski** [comment]
@sunboyy Can I stay with this repositories files ? I think everything in core file get code more difficulty to read and understand.

**Comment by sunboyy** [comment]
Sure!

**Comment by sunboyy** [comment]
@Martin89PL Are you going to change `src/recallcard/core.php`?

**Comment by MarcinGladkowski** [comment]
@sunboyy You can accept my PR or waiting for my solution. I find time to do this in one day,

**Comment by MarcinGladkowski** [comment]
@sunboyy Done. Could you check it, please ?

**Comment by sunboyy** [comment]
@Martin89PL I will find some time reviewing your PR. I am quite busy currently.

**Pull request merged**
